---
title: "R Notebook"
output: html_notebook
---

```{r}
# setwd("~/Google Drive/BARI/BARI Research Team Data Library/Permits") # project folder for building permits

options(scipen=100000000)

BARI <- "C:/Users/dobrien/OneDrive - Northeastern University/Documents/Research/Boston-Radcliffe/Data Platform/Data Update Checks/"

#---- packages
library(tidyverse)
library(sf)
library(magrittr)




#---- INPUT PATHS ----
permits2023_path <- "Building Permits/2023/Permits.Records.Geocoded.TY.202301.csv"
landParcels_path <- "GI/Parcel_final_20230405_TY_postsanitychecks.csv"
landParcelsShpPath = "GI/BARIParcels2022.shp"

propertyAssessment_path <- "GI/properties_geo_20230331_TY_postsanitychecks.csv" 

blockGroupsShpPath_10 = "GI/Census Block Groups.shp"
tractsShpPath_10 = "GI/Tracts_Boston_2010_BARI.shp"
blockGroupsShpPath_20 = "GI/Block_Groups_Boston_2020.shp"
tractsShpPath_20 = "GI/Tracts_Boston_2020.shp"

#---- OUTPUT PATHS ----
lpEcometricsPath = "Building Permits/2023/Parcels/"
lpEcometricsName = "Permits.Ecometrics.LP"

cbgEcometricsPath = "Building Permits/2023/CBG/"
cbgEcometricsName = "Permits.Ecometrics.CBG"

ctEcometricsPath = "Building Permits/2023/CT/"
ctEcometricsName = "Permits.Ecometrics.CT"

#---- READ IN DATA ----
permits = read.csv(paste0(BARI, permits2023_path),stringsAsFactors=FALSE)
landParcels = read.csv(paste0(BARI, landParcels_path), stringsAsFactors=F)
lps_shp = read_sf(paste0(BARI, landParcelsShpPath), stringsAsFactors=F)
cts_shp_10 = read_sf(paste0(BARI, tractsShpPath_10), stringsAsFactors=F)
bgs_shp_10 = read_sf(paste0(BARI, blockGroupsShpPath_10), stringsAsFactors=F)
cts_shp_20 = read_sf(paste0(BARI, tractsShpPath_20), stringsAsFactors=F)
bgs_shp_20 = read_sf(paste0(BARI, blockGroupsShpPath_20), stringsAsFactors=F)
propertyAssessment = read.csv(paste0(BARI, propertyAssessment_path),stringsAsFactors=F)
#---- PREP BEFORE AGGREGATION ----

#check out the data
sum(!is.na(permits$BG_ID_10))/length(permits$BG_ID_10) #0.977
sum(!is.na(permits$CT_ID_10))/length(permits$CT_ID_10) #0.977
sum(!is.na(permits$ISSUED_DATE))/length(permits$ISSUED_DATE) #1

#landParcels$Blk_ID_10 <- format(landParcels$Blk_ID_10, scientific = F)
#landParcels$CT_ID_10 <- format(landParcels$CT_ID_10, scientific = F)
#landParcels$BG_ID_10 <- format(landParcels$BG_ID_10, scientific = F)
#landParcels$Blk_ID_20 <- format(landParcels$Blk_ID_20, scientific = F)
#landParcels$CT_ID_20 <- format(landParcels$CT_ID_20, scientific = F)
#landParcels$BG_ID_20 <- format(landParcels$BG_ID_20, scientific = F)

#propertyAssessment$Blk_ID_10 <- format(propertyAssessment$Blk_ID_10, scientific = F)
#propertyAssessment$CT_ID_10 <- format(propertyAssessment$CT_ID_10, scientific = F)
#propertyAssessment$BG_ID_10 <- format(propertyAssessment$BG_ID_10, scientific = F)
#propertyAssessment$Blk_ID_20 <- format(propertyAssessment$Blk_ID_20, scientific = F)
#propertyAssessment$CT_ID_20 <- format(propertyAssessment$CT_ID_20, scientific = F)
#propertyAssessment$BG_ID_20 <- format(propertyAssessment$BG_ID_20, scientific = F)

#this doesn't depend on the year so i can do it outside the loop
#highlights the fact that we are using the same number of parcels for each year
lps_perBG = aggregate(Land_Parcel_ID ~ BG_ID_10, data=landParcels,length)
names(lps_perBG)[2]="numLandParcels"

lps_perBG_20 = aggregate(Land_Parcel_ID ~ BG_ID_20, data=landParcels,length)
names(lps_perBG_20)[2]="numLandParcels"
##there are 40 block groups not present in the permit data, but this is because they are trivial spaces at the border of the city that technically belong to other municipalities##

lps_perCT = aggregate(Land_Parcel_ID ~ CT_ID_10, data=landParcels,length)
names(lps_perCT)[2]="numLandParcels"

lps_perCT_20 = aggregate(Land_Parcel_ID ~ CT_ID_20, data=landParcels,length)
names(lps_perCT_20)[2]="numLandParcels"

lps_agg_long <- data.frame(Land_Parcel_ID = landParcels$Land_Parcel_ID)

cbgs_agg_long_10 <- lps_perBG
cts_agg_long_10 <- lps_perCT
cbgs_agg_long_20 <- lps_perBG_20
cts_agg_long_20 <- lps_perCT_20

names(cbgs_agg_long_10)[2] <- 'nLP'
names(cts_agg_long_10)[2] <- 'nLP'
names(cbgs_agg_long_20)[2] <- 'nLP'
names(cts_agg_long_20)[2] <- 'nLP'


cbgs_agg_long_shp_10 = merge(bgs_shp_10,lps_perBG,by.x = "GEOID10", by.y="BG_ID_10",all.x=T)
cts_agg_long_shp_10 = merge(cts_shp_10,lps_perCT,by.x = "GEOID10", by.y="CT_ID_10",all.x=T)
cbgs_agg_long_shp_20 = merge(bgs_shp_20,lps_perBG_20,by.x = "GEOID20", by.y="BG_ID_20",all.x=T)
cts_agg_long_shp_20 = merge(cts_shp_20,lps_perCT_20,by.x = "GEOID20", by.y="CT_ID_20",all.x=T)

# the government value
##“Government” Variable
permits$government = ifelse(permits$owner == "CITY OF BOSTON" |
                          permits$owner == "BOSTON REDEVELOPMNT AUTH" |
                          permits$owner == "BOSTON REDEVELOPMENT AUTH" |
                          permits$owner == "BOSTON REDEVELOPMENT" |
                          permits$owner == "BOSTON HOUSING AUTHORITY" |
                          permits$owner == "BOSTON HOUSING AUTH" |
                          permits$owner == "BOSTON POLICE POST 1018 VFW" |
                          permits$owner == "CITY OF BOSTON SCHOOL DEPT" |
                          permits$owner == "CITY OF BOSTON PUBLIC HEALTH" |
                          permits$owner == "CITY OF BOSTON SCHOOL DEPT" |
                          permits$owner == "CITY OF BOSTON BY FCL" |
                          permits$owner == "CITY OF BOSTON PUB FACIL" |
                          permits$owner == "BOSTON REDEVLOPMENT AUTHORIT" |
                          permits$owner == "BOSTON POLICE DETECTIVE" |
                          permits$owner == "CITY OF BOSTON PARKS" |
                          permits$owner == "BOSTON REDEVELOP AUTHORITY" |
                          permits$owner == "CITY OF BOSTON PARKS AND" |
                          permits$owner == "THE BOSTON REDEVELOPMENT" |
                          permits$owner == "BOSTON REDEVOPMENT AUTH" |
                          permits$owner == "BOSTON REDEVLPMNT AUTHOR" |
                          permits$owner == "BOSTON REDEVLOPMENT AUTHOR" |
                          permits$owner == "MBTA" |
                          permits$owner == "BOSTON PUBLIC HEALTH COMM" |
                          permits$owner == "CITY OF BOSTON PUBLIC HEALTH" |
                          permits$owner == "CITY OB BOSTON PUBLIC HEALTH" |
                          permits$owner == "PUBLIC FACILITIES COMM" |
                          permits$owner== "BOSTON DEVELOPMENT" |
                          permits$owner== "BOSTON FIRE DEPARTMENT" | 
                          permits$owner== "BOSTON HOUSING" | 
                          permits$owner== "BOSTON MUNRCIPA" | 
                          permits$owner== "BOSTON POLICE DEPARTMENT" | 
                          permits$owner== "BOSTON PORT * S" | 
                          permits$owner== "BOSTON PUBLIC HEALTH COMM" | 
                          permits$owner== "BOSTON REDEVELO" | 
                          permits$owner== "BOSTON REDEVELOPMENT AUTH" | 
                          permits$owner== "BOSTON REDEVELP" | 
                          permits$owner== "CITY OF BOSTON" | 
                          permits$owner== "CITY OF BOSTON - DND" | 
                          permits$owner== "CITY OF BOSTON - PUB FAC " | 
                          permits$owner== "CITY OF BOSTON (REO)" | 
                          permits$owner== "CITY OF BOSTON BY FCL" | 
                          permits$owner== "CITY OF BOSTON PROP MGMT DEPT" | 
                          permits$owner== "CITY OF BOSTON-GEORGE WHITE FUND" | 
                          permits$owner== "COMMONWLTH OF M" | 
                          permits$owner== "COMMWLTH OF MAS" | 
                          permits$owner== "M B T A" | 
                          permits$owner== "MASS BAY TRANSP" | 
                          permits$owner== "MASS BAY TRANSPORTATION AUTH" | 
                          permits$owner== "MASS PORT AUTHO" | 
                          permits$owner== "MASS PORT AUTHORITY" | 
                          permits$owner== "MASS TURNPIKE A" | 
                          permits$owner== "MASS TURNPIKE AUTHORITY" | 
                          permits$owner== "MASSACHUSETTS BAY TRANS AUTH" | 
                          permits$owner== "MASSACHUSETTS PORT AUTHORITY" | 
                          permits$owner== "MASSPORT AUTHOR" | 
                          permits$owner== "MBTA" | 
                          permits$owner== "MSS PORT AUTHOR" | 
                          permits$owner== "COMMMONWEALTH O" | 
                          permits$owner== "COMMONWEALTH FL" | 
                          permits$owner== "COMMONWEALTH OF" | 
                          permits$owner== "UNITED STATES OF AMER" | 
                          permits$owner== "FEDERAL HOME LOAN MORTGAGE" | 
                          permits$owner== "FEDERAL HOME LOAN MTG CORP" | 
                          permits$owner== "FEDERAL MORTGAGE ASSOC" | 
                          permits$owner== "FEDERAL NATIONAL MORTGAGE ASSO" | 
                          permits$owner== "FEDERAL NATIONAL MTG ASSOC",1,0)

####Aggregation at all levels####
#loops through for each year and does 2010 and 2020 geographies separately
# this loop is ~300 lines
lps_agg_long = merge(lps_agg_long,landParcels[c("Land_Parcel_ID","BG_ID_10","CT_ID_10","BG_ID_20","CT_ID_20")],by="Land_Parcel_ID",all.x=T)

for (i in c(2010:2022)){
  print(i)
 #i = 2022
  permits_sub = permits[year(permits$ISSUED_DATE)==i,]
  permits_sub$DECLARED_VALUATION_c99 = ifelse(permits_sub$DECLARED_VALUATION<0, 0,
                                          ifelse(permits_sub$DECLARED_VALUATION>quantile(permits_sub$DECLARED_VALUATION,.99, na.rm = TRUE),
                                                 quantile(permits_sub$DECLARED_VALUATION,.99, na.rm = TRUE),
                                                 permits_sub$DECLARED_VALUATION))
  temp = permits_sub[ permits_sub$newcon==1,]
  permits_sub_nd =  rbind(permits_sub[ permits_sub$newcon!=1, ],
                          temp[!duplicated(paste(temp$DECLARED_VALUATION,temp$Land_Parcel_ID)),])
  rm(temp)
  
  permits_sub_nd = permits_sub_nd[ !duplicated(permits_sub_nd$PermitNumber),]
  
  
  #aggregating
 
  types_byParcel  = aggregate( cbind(demo,newcon,addition,reno) ~ Land_Parcel_ID,data =permits_sub, FUN=sum, na.rm=T)
  
  
  names(types_byParcel) = c("Land_Parcel_ID","DEMO","NEWCON","ADD","RENO")
  types_byParcel2 = aggregate(cbind(((demo+newcon+addition+reno)*DECLARED_VALUATION_c99),
                                    ((demo+newcon+addition+reno)*DECLARED_VALUATION_c99*government))~Land_Parcel_ID, data = permits_sub_nd,FUN=sum,na.rm=T)
  names(types_byParcel2) = c("Land_Parcel_ID","DV","DV_public")
  types_byParcel = merge(types_byParcel,types_byParcel2,by="Land_Parcel_ID",all=T)
  
  types_byParcel$NEWCON[types_byParcel$NEWCON > 0 ]=1
  types_byParcel$DEMO = ifelse(types_byParcel$NEWCON == 1,0,ifelse(types_byParcel$DEMO>0,1,0))
  types_byParcel$ADD = ifelse(types_byParcel$NEWCON == 1 | types_byParcel$DEMO == 1,0,ifelse(types_byParcel$ADD>0,1,0))
  types_byParcel$RENO = ifelse(types_byParcel$NEWCON == 1 | types_byParcel$DEMO == 1 | types_byParcel$ADD == 1,0,ifelse(types_byParcel$RENO > 0,1,0))

  
  types_byParcel = types_byParcel[!is.na(types_byParcel$Land_Parcel_ID) & (!types_byParcel$Land_Parcel_ID==0),]

  types_byParcel = merge(types_byParcel,landParcels[c("Land_Parcel_ID","BG_ID_10","CT_ID_10","BG_ID_20","CT_ID_20")],by="Land_Parcel_ID",all.x=T)

    # output this year's file out:
  write.csv(types_byParcel,paste0(BARI, paste(c(lpEcometricsPath,"/",lpEcometricsName,".",i,".csv"),collapse="")),row.names=F)
  
  # rename the data frame so it persists
  assign(paste("types_byParcel",i,sep="_"), types_byParcel)

# append years to colnames for wide longitudinal format:
names(types_byParcel)[2:7] = paste(names(types_byParcel)[2:7], i, sep=".")
lps_agg_long <- merge(lps_agg_long,types_byParcel[1:7],by='Land_Parcel_ID',all.x=TRUE)
lps_agg_long[is.na(lps_agg_long[ncol(lps_agg_long)]),(ncol(lps_agg_long)-5):ncol(lps_agg_long)] <-0
lps_shp = merge(lps_shp,types_byParcel[1:7],by.x ="Ln_P_ID", by.y ="Land_Parcel_ID", all.x=T)

# aggregating to CBG level ####
#2010#
  print("aggregating to CBG level")
  types_byParcel_i <- get(paste0("types_byParcel_", i))
  cbgs_agg_10 = aggregate(cbind(DEMO, NEWCON, ADD, RENO,
                             DEMO*DV, NEWCON*DV, ADD*DV, RENO*DV,DV_public)~BG_ID_10, data= types_byParcel_i, FUN=sum,na.rm=T)
  names(cbgs_agg_10)[2:ncol(cbgs_agg_10)] = c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                                        "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")

    # merge on the number of lps in the cbg
  cbgs_agg_10 = merge(cbgs_agg_10, lps_perBG, by="BG_ID_10",all=T)
  # make 0s for any CT ids that were not in the aggregation
  cbgs_agg_10[is.na(cbgs_agg_10$DEMO_count),c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                                        "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")]=0

  # divide by number of LPs
  cbgs_agg_10[,c("DEMO_PP","NEWCON_PP","ADD_PP","RENO_PP",
              "DEMO_DV_PP","NEWCON_DV_PP","ADD_DV_PP","RENO_DV_PP","Public_DV_PP")] =
    cbgs_agg_10[,c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")] / cbgs_agg_10$numLandParcels


  # make the alteration to existing structure var
  cbgs_agg_10[,c("ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP")] =
    cbgs_agg_10[,c("ADD_count","ADD_PP","ADD_DV_PP")] +
    cbgs_agg_10[,c("DEMO_count","DEMO_PP","DEMO_DV_PP")] +
    cbgs_agg_10[,c("RENO_count","RENO_PP","RENO_DV_PP")]


  cbgs_agg_10[,c("TOTAL_count","TOTAL_PP","TOTAL_DV_PP")] =
    cbgs_agg_10[,c("NEWCON_count","NEWCON_PP","NEWCON_DV_PP")] +
    cbgs_agg_10[,c("ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP")]

  # reorder the variables and save the CSV
  cbgs_agg_10 = cbgs_agg_10[,c("BG_ID_10","numLandParcels",
                         "NEWCON_count", "NEWCON_PP","NEWCON_DV_PP", "DEMO_count", "DEMO_PP", "DEMO_DV_PP",
                         "ADD_count","ADD_PP","ADD_DV_PP","RENO_count","RENO_PP","RENO_DV_PP",
                         "ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP",
                         "TOTAL_count","TOTAL_PP","TOTAL_DV_PP",
                         "Public_DV_PP")]
names(cbgs_agg_10)

  write.csv(cbgs_agg_10,paste0(BARI,paste(c(cbgEcometricsPath,cbgEcometricsName,"2010.",i,".csv"),collapse="")),row.names=F)

  # rename the data frame so it persists
  assign(paste("cbgs_agg_10",i,sep="_"), cbgs_agg_10)
  cbgs_agg_long_10<-merge(cbgs_agg_long_10,cbgs_agg_10[c(1,3:11)],by='BG_ID_10',all.x=TRUE)
  names(cbgs_agg_long_10)[(ncol(cbgs_agg_long_10)-8):ncol(cbgs_agg_long_10)]<-paste(names(cbgs_agg_long_10)[(ncol(cbgs_agg_long_10)-8):ncol(cbgs_agg_long_10)],i,sep=".")

  # change names for the shp
  names(cbgs_agg_10) = c("BG_ID_10","nLP","NC_c","NC_PP", "NC_DV", "D_c",  "D_PP" , "D_DV",
                       "A_c", "A_PP","A_DV","R_c", "R_PP","R_DV","AS_c", "AS_pp", "AS_DV","T_c","T_PP","T_DV",
                      "P_DV")
  
  
  cbgs_agg_10 <- subset(cbgs_agg_10, select = -c(nLP))

  bgs_shp_10 = merge(bgs_shp_10[1:23], cbgs_agg_10,by.x="GEOID10", by.y="BG_ID_10",all.x=T)
  names(bgs_shp_10)
  write_sf(bgs_shp_10, dsn = paste0(BARI,paste(c(cbgEcometricsPath),collapse="")),layer = paste("Permits.Ecometrics.CBG2010",i,sep="."), driver="ESRI Shapefile", append=F)
  
    # rename for long shapefile
  names(cbgs_agg_10)[3:ncol(cbgs_agg_10)] = paste(names(cbgs_agg_10)[3:ncol(cbgs_agg_10)],gsub(pattern = "20","",as.character(i)),sep=".")
  # merge for long shapefile and dropping numLandParcels column

  cbgs_agg_long_shp_10 = merge(cbgs_agg_long_shp_10,cbgs_agg_10[,-3],by.x="GEOID10",by.y="BG_ID_10", all.x=T)

  #2020#
    print("CBG-2020")
  cbgs_agg_20 = aggregate(cbind(DEMO, NEWCON, ADD, RENO,
                             DEMO*DV, NEWCON*DV, ADD*DV, RENO*DV,DV_public)~BG_ID_20, data= types_byParcel_i, FUN=sum,na.rm=T)
  names(cbgs_agg_20)[2:ncol(cbgs_agg_20)] = c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                                        "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")

    # merge on the number of lps in the cbg
  cbgs_agg_20 = merge(cbgs_agg_20, lps_perBG_20, by="BG_ID_20",all=T)
  # make 0s for any CT ids that were not in the aggregation
  cbgs_agg_20[is.na(cbgs_agg_20$DEMO_count),c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                                        "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")]=0

  # divide by number of LPs
  cbgs_agg_20[,c("DEMO_PP","NEWCON_PP","ADD_PP","RENO_PP",
              "DEMO_DV_PP","NEWCON_DV_PP","ADD_DV_PP","RENO_DV_PP","Public_DV_PP")] =
    cbgs_agg_20[,c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")] / cbgs_agg_20$numLandParcels


  # make the alteration to existing structure var
  cbgs_agg_20[,c("ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP")] =
    cbgs_agg_20[,c("ADD_count","ADD_PP","ADD_DV_PP")] +
    cbgs_agg_20[,c("DEMO_count","DEMO_PP","DEMO_DV_PP")] +
    cbgs_agg_20[,c("RENO_count","RENO_PP","RENO_DV_PP")]


  cbgs_agg_20[,c("TOTAL_count","TOTAL_PP","TOTAL_DV_PP")] =
    cbgs_agg_20[,c("NEWCON_count","NEWCON_PP","NEWCON_DV_PP")] +
    cbgs_agg_20[,c("ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP")]

  # reorder the variables and save the CSV
  cbgs_agg_20 = cbgs_agg_20[,c("BG_ID_20","numLandParcels",
                         "NEWCON_count", "NEWCON_PP","NEWCON_DV_PP", "DEMO_count", "DEMO_PP", "DEMO_DV_PP",
                         "ADD_count","ADD_PP","ADD_DV_PP","RENO_count","RENO_PP","RENO_DV_PP",
                         "ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP",
                         "TOTAL_count","TOTAL_PP","TOTAL_DV_PP",
                         "Public_DV_PP")]
names(cbgs_agg_20)

  write.csv(cbgs_agg_20,paste0(BARI,paste(c(cbgEcometricsPath,cbgEcometricsName,"2020.",i,".csv"),collapse="")),row.names=F)

  # rename the data frame so it persists
  assign(paste("cbgs_agg_20",i,sep="_"), cbgs_agg_20)
  cbgs_agg_long_20<-merge(cbgs_agg_long_20,cbgs_agg_20[c(1,3:11)],by='BG_ID_20',all.x=TRUE)
  names(cbgs_agg_long_20)[(ncol(cbgs_agg_long_20)-8):ncol(cbgs_agg_long_20)]<-paste(names(cbgs_agg_long_20)[(ncol(cbgs_agg_long_20)-8):ncol(cbgs_agg_long_20)],i,sep=".")


  # change names for the shp
  names(cbgs_agg_20) = c("BG_ID_20","nLP","NC_c","NC_PP", "NC_DV", "D_c",  "D_PP" , "D_DV",
                       "A_c", "A_PP","A_DV","R_c", "R_PP","R_DV","AS_c", "AS_pp", "AS_DV","T_c","T_PP","T_DV",
                      "P_DV")
  
  
  cbgs_agg_20 <- subset(cbgs_agg_20, select = -c(nLP))

  bgs_shp_20 = merge(bgs_shp_20[1:14], cbgs_agg_20,by.x="GEOID20", by.y="BG_ID_20",all.x=T)
  names(bgs_shp_20)
  write_sf(bgs_shp_20, dsn = paste0(BARI,paste(c(cbgEcometricsPath),collapse="")),layer = paste("Permits.Ecometrics.CBG2020",i,sep="."), driver="ESRI Shapefile", append=F)

    # rename for long shapefile
  names(cbgs_agg_20)[3:ncol(cbgs_agg_20)] = paste(names(cbgs_agg_20)[3:ncol(cbgs_agg_20)],gsub(pattern = "20","",as.character(i)),sep=".")
  # merge for long shapefile and dropping numLandParcels column

  cbgs_agg_long_shp_20 = merge(cbgs_agg_long_shp_20,cbgs_agg_20[,-3],by.x="GEOID20",by.y="BG_ID_20", all.x=T)


  ### aggregating to CT level ####
  print("aggregating to CT level")
  
  #2010#
  cts_agg_10 = aggregate(cbind(DEMO, NEWCON, ADD, RENO,
                             DEMO*DV, NEWCON*DV, ADD*DV, RENO*DV,DV_public)~CT_ID_10, data= types_byParcel_i, FUN=sum,na.rm=T)
  names(cts_agg_10)[2:ncol(cts_agg_10)] = c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                                        "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")

    # merge on the number of lps in the ct
  cts_agg_10 = merge(cts_agg_10, lps_perCT, by="CT_ID_10",all=T)
  # make 0s for any CT ids that were not in the aggregation
  cts_agg_10[is.na(cts_agg_10$DEMO_count),c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                                        "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")]=0

  # divide by number of LPs
  cts_agg_10[,c("DEMO_PP","NEWCON_PP","ADD_PP","RENO_PP",
              "DEMO_DV_PP","NEWCON_DV_PP","ADD_DV_PP","RENO_DV_PP","Public_DV_PP")] =
    cts_agg_10[,c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")] / cts_agg_10$numLandParcels


  # make the alteration to existing structure var
  cts_agg_10[,c("ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP")] =
    cts_agg_10[,c("ADD_count","ADD_PP","ADD_DV_PP")] +
    cts_agg_10[,c("DEMO_count","DEMO_PP","DEMO_DV_PP")] +
    cts_agg_10[,c("RENO_count","RENO_PP","RENO_DV_PP")]


  cts_agg_10[,c("TOTAL_count","TOTAL_PP","TOTAL_DV_PP")] =
    cts_agg_10[,c("NEWCON_count","NEWCON_PP","NEWCON_DV_PP")] +
    cts_agg_10[,c("ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP")]

  # reorder the variables and save the CSV
  cts_agg_10 = cts_agg_10[,c("CT_ID_10","numLandParcels",
                         "NEWCON_count", "NEWCON_PP","NEWCON_DV_PP", "DEMO_count", "DEMO_PP", "DEMO_DV_PP",
                         "ADD_count","ADD_PP","ADD_DV_PP","RENO_count","RENO_PP","RENO_DV_PP",
                         "ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP",
                         "TOTAL_count","TOTAL_PP","TOTAL_DV_PP",
                         "Public_DV_PP")]
names(cts_agg_10)

  write.csv(cts_agg_10,paste0(BARI,paste(c(ctEcometricsPath,ctEcometricsName,"2010.",i,".csv"),collapse="")),row.names=F)

  # rename the data frame so it persists
  assign(paste("cts_agg_10",i,sep="_"), cts_agg_10)
  cts_agg_long_10<-merge(cts_agg_long_10,cts_agg_10[c(1,3:11)],by='CT_ID_10',all.x=TRUE)
  names(cts_agg_long_10)[(ncol(cts_agg_long_10)-8):ncol(cts_agg_long_10)]<-paste(names(cts_agg_long_10)[(ncol(cts_agg_long_10)-8):ncol(cts_agg_long_10)],i,sep=".")


  # change names for the shp
  names(cts_agg_10) = c("CT_ID_10","nLP","NC_c","NC_PP", "NC_DV", "D_c",  "D_PP" , "D_DV",
                       "A_c", "A_PP","A_DV","R_c", "R_PP","R_DV","AS_c", "AS_pp", "AS_DV","T_c","T_PP","T_DV",
                      "P_DV")
  
  
  cts_agg_10 <- subset(cts_agg_10, select = -c(nLP))

  cts_shp_10 = merge(cts_shp_10[1:16], cts_agg_10,by.x="GEOID10", by.y="CT_ID_10",all.x=T)
  names(cts_shp_10)
  write_sf(cts_shp_10, dsn = paste0(BARI,paste(c(ctEcometricsPath),collapse="")),layer = paste("Permits.Ecometrics.CT2010",i,sep="."), driver="ESRI Shapefile", append=F)

    # rename for long shapefile
  names(cts_agg_10)[3:ncol(cts_agg_10)] = paste(names(cts_agg_10)[3:ncol(cts_agg_10)],gsub(pattern = "20","",as.character(i)),sep=".")
  # merge for long shapefile and dropping numLandParcels column

  cts_agg_long_shp_10 = merge(cts_agg_long_shp_10,cts_agg_10[,-3],by.x="GEOID10",by.y="CT_ID_10", all.x=T)

  #2020#
    print("CT-2020")
  cts_agg_20 = aggregate(cbind(DEMO, NEWCON, ADD, RENO,
                             DEMO*DV, NEWCON*DV, ADD*DV, RENO*DV,DV_public)~CT_ID_20, data= types_byParcel_i, FUN=sum,na.rm=T)
  names(cts_agg_20)[2:ncol(cts_agg_20)] = c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                                        "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")

    # merge on the number of lps in the ct
  cts_agg_20 = merge(cts_agg_20, lps_perCT_20, by="CT_ID_20",all=T)
  # make 0s for any CT ids that were not in the aggregation
  cts_agg_20[is.na(cts_agg_20$DEMO_count),c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                                        "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")]=0

  # divide by number of LPs
  cts_agg_20[,c("DEMO_PP","NEWCON_PP","ADD_PP","RENO_PP",
              "DEMO_DV_PP","NEWCON_DV_PP","ADD_DV_PP","RENO_DV_PP","Public_DV_PP")] =
    cts_agg_20[,c("DEMO_count","NEWCON_count","ADD_count","RENO_count",
                "DEMO_DV","NEWCON_DV","ADD_DV","RENO_DV","Public_DV")] / cts_agg_20$numLandParcels


  # make the alteration to existing structure var
  cts_agg_20[,c("ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP")] =
    cts_agg_20[,c("ADD_count","ADD_PP","ADD_DV_PP")] +
    cts_agg_20[,c("DEMO_count","DEMO_PP","DEMO_DV_PP")] +
    cts_agg_20[,c("RENO_count","RENO_PP","RENO_DV_PP")]


  cts_agg_20[,c("TOTAL_count","TOTAL_PP","TOTAL_DV_PP")] =
    cts_agg_20[,c("NEWCON_count","NEWCON_PP","NEWCON_DV_PP")] +
    cts_agg_20[,c("ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP")]

  # reorder the variables and save the CSV
  cts_agg_20 = cts_agg_20[,c("CT_ID_20","numLandParcels",
                         "NEWCON_count", "NEWCON_PP","NEWCON_DV_PP", "DEMO_count", "DEMO_PP", "DEMO_DV_PP",
                         "ADD_count","ADD_PP","ADD_DV_PP","RENO_count","RENO_PP","RENO_DV_PP",
                         "ALTSTRUCT_count","ALTSTRUCT_PP","ALTSTRUCT_DV_PP",
                         "TOTAL_count","TOTAL_PP","TOTAL_DV_PP",
                         "Public_DV_PP")]
names(cts_agg_20)

  write.csv(cts_agg_20,paste0(BARI,paste(c(ctEcometricsPath,ctEcometricsName,"2020.",i,".csv"),collapse="")),row.names=F)

  # rename the data frame so it persists
  assign(paste("cts_agg_20",i,sep="_"), cts_agg_20)
  cts_agg_long_20<-merge(cts_agg_long_20,cts_agg_20[c(1,3:11)],by='CT_ID_20',all.x=TRUE)
  names(cts_agg_long_20)[(ncol(cts_agg_long_20)-8):ncol(cts_agg_long_20)]<-paste(names(cts_agg_long_20)[(ncol(cts_agg_long_20)-8):ncol(cts_agg_long_20)],i,sep=".")


  
  # change names for the shp
  names(cts_agg_20) = c("CT_ID_20","nLP","NC_c","NC_PP", "NC_DV", "D_c",  "D_PP" , "D_DV",
                       "A_c", "A_PP","A_DV","R_c", "R_PP","R_DV","AS_c", "AS_pp", "AS_DV","T_c","T_PP","T_DV",
                      "P_DV")
  
  
  cts_agg_20 <- subset(cts_agg_20, select = -c(nLP))

  cts_shp_20 = merge(cts_shp_20[1:14], cts_agg_20,by.x="GEOID20", by.y="CT_ID_20",all.x=T)
  names(cts_shp_20)
  write_sf(cts_shp_20, dsn = paste0(BARI,paste(c(ctEcometricsPath),collapse="")),layer = paste("Permits.Ecometrics.CT2020",i,sep="."), driver="ESRI Shapefile", append=F)

    # rename for long shapefile
  names(cts_agg_20)[3:ncol(cts_agg_20)] = paste(names(cts_agg_20)[3:ncol(cts_agg_20)],gsub(pattern = "20","",as.character(i)),sep=".")
  # merge for long shapefile and dropping numLandParcels column

  cts_agg_long_shp_20 = merge(cts_agg_long_shp_20,cts_agg_20[,-3],by.x="GEOID20",by.y="CT_ID_20", all.x=T)

  

}

#longtiduinal####
#write longitudinal LPs
write.csv(lps_agg_long,paste0(BARI, paste(c(lpEcometricsPath,lpEcometricsName,".Longitudinal.csv"),collapse="")),row.names=F)

# write longitudinal CBG 

write.csv(cbgs_agg_long_10,paste0(BARI, paste(c(cbgEcometricsPath,cbgEcometricsName,"10.Longitudinal.csv"),collapse="")),row.names=F)
write.csv(cbgs_agg_long_20,paste0(BARI, paste(c(cbgEcometricsPath,cbgEcometricsName,"20.Longitudinal.csv"),collapse="")),row.names=F)
write_sf(cbgs_agg_long_shp_10, dsn = paste0(BARI,paste(c(cbgEcometricsPath),collapse="")),layer = "Permits.Ecometrics.CBG2010.Longitudinal", driver="ESRI Shapefile", append=F)
write_sf(cbgs_agg_long_shp_20, dsn = paste0(BARI,paste(c(cbgEcometricsPath),collapse="")),layer = "Permits.Ecometrics.CBG2020.Longitudinal", driver="ESRI Shapefile", append=F)
  

# write longitudinal CT 
write.csv(cts_agg_long_10,paste0(BARI, paste(c(ctEcometricsPath,ctEcometricsName,"10.Longitudinal.csv"),collapse="")),row.names=F)
write.csv(cts_agg_long_20,paste0(BARI, paste(c(ctEcometricsPath,ctEcometricsName,"20.Longitudinal.csv"),collapse="")),row.names=F)
write_sf(cts_agg_long_shp_10, dsn = paste0(BARI,paste(c(ctEcometricsPath),collapse="")),layer = "Permits.Ecometrics.CT2010.Longitudinal", driver="ESRI Shapefile", append=F)
write_sf(cts_agg_long_shp_20, dsn = paste0(BARI,paste(c(ctEcometricsPath),collapse="")),layer = "Permits.Ecometrics.CT2020.Longitudinal", driver="ESRI Shapefile", append=F)

   # identify columns to remove
temp_cbgs_agg_long <- grep("\\.(x|y)$", names(temp_cbgs_agg_long))

# remove columns that end with ".x" and ".y"
temp_cbgs_agg_long <- subset(temp_cbgs_agg_long, select = -columns_to_remove_cbg)
  temp_cbgs_agg_long <- rownames(temp_cbgs_agg_long, do.NULL = TRUE)

  # identify columns to remove
temp_cts_agg_long <- grep("\\.(x|y)$", names(temp_cts_agg_long))

# remove columns that end with ".x" and ".y"
temp_cts_agg_long <- subset(temp_cts_agg_long, select = -columns_to_remove_cbg)
  temp_cts_agg_long <- rownames(temp_cts_agg_long, do.NULL = TRUE)

